export const SET_INITIAL_POKEMON_DATA_SUCCESS = 'SET_INITIAL_POKEMON_DATA_SUCCESS';
export const SET_INITIAL_POKEMON_DATA_FAIL = 'SET_INITIAL_POKEMON_DATA_FAIL';
export const SET_FINAL_POKEMON_DATA_SUCCESS = 'SET_INITI_FINAL_POKEMON_DATA_SUCCESS';
export const SET_FINAL_POKEMON_DATA_FAIL = 'SET_INITI_FINAL_POKEMON_DATA_FAIL';
export const SET_REQUESTED_POKEMON = 'SET_REQUESTED_POKEMON';
export const IS_LOADING = 'IS_LOADING';
export const SET_SEARCHVALUE = 'SET_SEARCHVALUE';
// export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
